import Head from 'next/head'
import React from 'react'

const Overview = () => {
  return (
    <>
      <Head>
        <title>Event Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div></div>
      <div className="container-flex pt-24">
        <div className="grid grid-cols-3 gap-4">
          <div className="col-span-2">
            <div className="card">
              <div className="card-header">
                <h3>
                  <a className="text-info">Title</a>
                </h3>
                <div>
                  <strong></strong>
                </div>
              </div>
              <div className="card-body">
                <span> </span>
                <button className="bg-gray-200 text-red-500">Vise</button>
              </div>
            </div>
            <br />
          </div>
          <div className="col-span-1"></div>
        </div>
      </div>
    </>
  )
}

export default Overview
