import Head from 'next/head'
import React, { useEffect } from 'react'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { useForm, useWatch } from 'react-hook-form'
import eventService from '@/services/event'

export default function Edit (){
  const router = useRouter();
  const [message, setMessage] = useState(null)
  const [event, setEvent] = useState(null)

  const onSubmit = async (data) => {
      const event = await eventService.update({...data, id: router.query.id});
      if (event.status === 500) {
        return setMessage(event.message);
      }
        router.push('/event/dashboard');
  };
  useEffect(()=> {
    let id=router.query.id
    showEvent(id)
  }, [])

  async function showEvent (id){
    let event = await eventService.show(id)
    setEvent(event)
  }

  const { register, handleSubmit, formState: { errors } } = useForm({
    defaultValues: async () => await eventService.show(router.query.id)
  });

  return (
    <>
      <Head>
        <title>Event Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="mt-28">
        <div className="container mx-auto">
          <div className="max-w-md mx-auto pb-12">
            <div className="bg-white p-8 rounded-lg shadow-lg shadow-gray-800">
              <h2 className="text-center text-black text-2xl font-bold mb-6">Event editing</h2>
              
              <form onSubmit={handleSubmit(onSubmit)}>
            

                <div className="mb-4">
                  <label className="block font-medium">New title</label>
                    <input
                      type="text"
                      id="title"
                      className="w-full px-4 py-2 border border-gray-300 rounded focus:outline-none focus:border-blue-500"
                      name="title"
                      placeholder="Enter the new title"
                      {...register('title')}/>
                  <p className="text-red-500"></p>
                </div>

                <div className="mb-4">
                  <label htmlFor="shortDescription" className="block font-medium">Short description</label>
                    <textarea
                      id="shortDescription"
                      className="w-full px-4 py-2 border border-gray-300 rounded focus:outline-none focus:border-blue-500"
                      name="shortDescription"
                      rows="3"
                      placeholder="Describe the event"
                      {...register('short_description')}>
                    </textarea>
                  <p className="text-red-500"></p>
                </div>

                <div className="mb-4">
                  <label htmlFor="content" className="block font-medium">Content</label>
                    <textarea
                      id="content"
                      className="w-full px-4 py-2 border border-gray-300 rounded focus:outline-none focus:border-blue-500"
                      name="content"
                      rows="12"
                      placeholder="Enter post content"
                      {...register('content')}>
                    </textarea>
                  <p className="text-red-500"></p>
                </div>
                
                <button type="submit" className="bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded-md">Commit changes</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

