import Head from 'next/head'
import React from 'react'

const Overview = () => {
  return (
    <>
      <Head>
        <title>Event Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div></div>
      <div className="h-full bg-black grid grid-cols-5 grid-rows-5 gap-7 ml-2 mr-2 mt-2 pb-2 justify-center">
    <div className="col-span-5 bg-white h-16 ml-64 mr-2 mt-2">
      <label>TITLE</label>
    </div>
    <div className="col-span-2 row-span-4 row-start-2 bg-blue-500 ml-2 mr-2">IMAGE</div>
    <div className="col-span-3 col-start-3 h-24 row-start-2 bg-teal-500 ml-2 mr-2">SHORT DESCRIPTION</div>
    <div className="col-span-3 row-span-3 col-start-3 row-start-3 bg-red-400 ml-2 mr-2">CONTENT</div>
</div>
    </>
  )
}

export default Overview
