import React from 'react'
import Head from 'next/head'
import { useForm } from 'react-hook-form'
import { useRouter } from 'next/router';
import { useState } from 'react';
import userService from '@/services/user';
import Link from 'next/link';

const Login = () => {
  const router = useRouter();
  const [message, setMessage] = useState(null)
  const { register, handleSubmit, formState: { errors } } = useForm();
  const onSubmit = async (data) => {
      const user = await userService.login(data);
  
      if (user.status === 500) {
        return setMessage(user.message);
      }
        router.push('/event/dashboard');
  };
  
  return (
    <>
      <Head>
        <title>Event Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="mt-16">
        <div className="container mx-auto">
          <div className="max-w-lg py-16 mx-auto">
            <div className="bg-purple-600 bg-opacity-60 p-14 m-2 rounded-lg shadow-lg shadow-pink-800">
              <h2 className="text-center text-white text-2xl font-bold mb-4">Log in form</h2>
              <form onSubmit={handleSubmit(onSubmit)}>
                <div className="mb-4">
                  <label htmlFor="email" className="block mb-2 text-white">Email</label>
                  <input
                    {...register("email")}
                    type="text"
                    id="email"
                    name="email"
                    className="w-full px-4 py-2 bg-pink-500 bg-opacity-70 border border-gray-300 rounded focus:outline-none focus:border-pink-600 placeholder:text-slate-300"
                    placeholder="Enter your email"
                  />
                </div>
                <div className="mb-4">
                  <label htmlFor="password" className="block text-white">Password</label>
                  <input
                    {...register("password")}
                    type="password"
                    id="password"
                    name="password"
                    className="w-full px-4 py-2 bg-pink-500 bg-opacity-70 border border-gray-300 rounded focus:outline-none focus:border-pink-600 placeholder:text-slate-300"
                    placeholder="Enter your password"
                  />
                </div>
                <div className="flex items-center">
                  <button type="submit" className="bg-blue-500 text-white text-center px-2 py-2 rounded hover:bg-blue-600">Submit</button>
                  <span className="text-dark text-md px-4 text-center"> Not registered?
                    <Link className='text-blue-300 hover:text-blue-400 px-2 underline' href='/register'>Do it here!</Link>
                  </span>
                </div>
              </form>
              {message && <div className='text-red-500'>{message}</div>}
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Login;
